CREATE DATABASE IF NOT EXISTS CatDB;
USE CatDB;
CREATE TABLE IF NOT EXISTS Cats (
    CatID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Breed VARCHAR(50),
    Age INT,
    Color VARCHAR(30),
    OwnerName VARCHAR(100)
);